### ISSUE TITLE
Définition générale du projet

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_ZH#1]
CCTP initial : https://geonature.fr/documents/cctp/2020-07-24-SIT_ZH_CCTP.pdf
CCTP annexe MCD : https://geonature.fr/documents/cctp/2020-07-24-SIT_ZH_CCTP_Doc_technique_MCD.pdf

- Développement d'un module GeoNature d'inventaire des Zones Humides (ZH)
- Commande : PNR Luberon (avec SIT PNR PACA, Agence de l'eau PACA et DREAL PACA)
- Prestation de développements : Natural Solutions
- Inventaire des ZH + Évaluation et hiérarchisation des ZH + Module de consultation public

**Comment by Arnoul** [comment]
Pour mieux cerner le contexte du projet et l'origine première de la base de données, plus d'informations sur la page du SIT interparc paca : http://geo.pnrpaca.org/portail-geographique-des-zones-humides-de-provence-alpes-cote-dazur/

**Comment by JulienCorny** [comment]
Voici le CCTP-annexe tutoriel expert qui permet d'avoir l'ensemble des fonctionnalités de l'appli et qui a été utilisé pour construire le MCD #3 
[SIT_ZH_CCTP-Annexe-Tutoriel-Expert.pdf](https://github.com/PnX-SI/gn_module_ZH/files/5893379/SIT_ZH_CCTP-Annexe-Tutoriel-Expert.pdf)

**Comment by camillemonchicourt** [comment]
Une première version fonctionnelle du module a été développée et publiée - https://github.com/PnX-SI/gn_module_ZH/releases
