### ISSUE TITLE
pas de SRID sur geom lors de la creation, modification de geometrie

### ISSUE THREAD

**Issue by Arnoul** [PnX-SI/gn_module_ZH#13]
Lors de la création d'une zone humide sur l'appli, pas de SRID sur la geom.
Si on modifie une zone humide il remet le SRID à 0

**Comment by camillemonchicourt** [comment]
En effet, on voit sur les scripts de création de la BDD qu les géométries sont créées sans SRID : https://github.com/PnX-SI/gn_module_ZH/blob/main/data/script_create_tables.sql#L250

C'est le cas pour les géométries des ZH, mais aussi des bassins versants, etc...

C'est pas une bonne chose du tout en effet.

Il faudrait faire comme dans GeoNature, et utiliser le SRID défini en paramètre, lors de la création de la BDD : https://github.com/PnX-SI/GeoNature/blob/master/backend/geonature/migrations/data/core/synthese.sql#L148

En métropole, le SRID sera 2154, mais dans les DOM-TOM ce sera autre chose.

Le paramètre à utiliser est ici : https://github.com/PnX-SI/GeoNature/blob/master/config/settings.ini.sample#L43

Et ici on voit comment on récupère ce paramètre pour l'utiliser quand on créer la BDD de GeoNature avec le bon SRID défini en paramètre : https://github.com/PnX-SI/GeoNature/blob/master/install/03_create_db.sh#L103-L104

**Comment by bouttier** [comment]
Une fois la base de GeoNature créé, lorsque l’on a besoin du SRID, on le récupère ainsi :
```
SELECT FIND_SRID('ref_geo', 'l_areas', 'geom')
```
Exemple : https://github.com/PnX-SI/RefGeo/blob/master/src/ref_geo/utils.py#L7

**Comment by camillemonchicourt** [comment]
Il n'y a pas de géométrie locale dans la BDD. Les géométries sont stockées en 4326.
La déclaration du SRID 4326 des géométries de la BDD est réalisée dans cette migration : https://github.com/PnX-SI/gn_module_ZH/commit/7d77aa82c54703b8eac8eba41c85495b062e71e7

Cela a nécessité de supprimer les vues utilisant les champs de géométrie et de les recréer après avoir défini le SRID des champs de géométrie.

**Comment by camillemonchicourt** [comment]
Corrigé dans la version 1.1.0, en définissant tous les champs de géométrie en 4326.
