### ISSUE TITLE
Erreur serveur sur moteur de recherche multi-critères

### ISSUE THREAD

**Issue by Arnoul** [PnX-SI/gn_module_ZH#14]
Il y a une erreur serveur sur la "recherche multi-critères" sur les bassins versants qui n'ont pas de règles de hiérarchisation.  la "recherche multi-critères" et la "recherche hiérarchisation" sont, en principe, deux choses.
Pour le SIT-ZH, un exemple sur le premier bassin versant de la liste  "Affluent Haute-Durance DU_12_01".

**Comment by camillemonchicourt** [comment]
Corrigé dans la version 1.1.0
