### ISSUE TITLE
v1_MCD

### ISSUE THREAD

**Issue by JulienCorny** [PnX-SI/gn_module_ZH#3]
Voici une 1ere version du MCD
![mcd_v1_corrected](https://user-images.githubusercontent.com/40057801/106265979-1d9d6400-6228-11eb-85c8-fef917f80a85.jpg)

**Comment by JulienCorny** [comment]
le pdf avec plus de détails sur les tables
[mcd_v1_corrected.pdf](https://github.com/PnX-SI/gn_module_ZH/files/5893333/mcd_v1_corrected.pdf)

**Comment by JulienCorny** [comment]
Le MCD est basé sur les infos des documents de l'issue #1 , et particulièrement le CCTP-annexe tutoriel expert

**Comment by camillemonchicourt** [comment]
Le MCD a évolué depuis et une première version fonctionnelle du module a été développée et publiée - https://github.com/PnX-SI/gn_module_ZH/releases
