### ISSUE TITLE
Interface Web du module Zones Humides: impossibilité de visualiser les données une fois enregistrées

### ISSUE THREAD

**Issue by Ericlf19** [PnX-SI/gn_module_ZH#4]
Cher développeurs de Géonature,
Bonjour,
Je suis stagiaire en Géomatique au sein du Conservatoire d'Espace Naturels de Haute-Savoie.

Je me permets de vous contacter car lors de la saisie de données dans le module Zones Humides, j'ai constaté qu'une fois les données enregistrées dans le module, on ne peut pourtant pas les visualiser : les données n'apparaissent ni sur la carte située à gauche du module de saisie, ni dans le volet de droite censé afficher les données. On peut d'ailleurs voir sur la capture d'écran ci-dessous qu'un onglet rouge apparaît pour avertir l'utilisateur qu'une erreur s'est produite.
![capture_ecran_module_zones_humides](https://user-images.githubusercontent.com/103249990/185889201-4f293c4a-4303-46b8-b642-87aa24bb4592.png)

Cette erreur n'apparaît pas pour d'autres modules de saisie de données (ici pour la saisie des données Occtax): 
![capture_occtax](https://user-images.githubusercontent.com/103249990/185889261-62374a15-ab9e-434b-b3ab-3621fa7284b5.png)

Pourtant, ces informations sont bien présentes dans la base de données du module Zones Humides: 
![capture_ecran_pr_zh](https://user-images.githubusercontent.com/103249990/185889307-0e147ff0-1d0a-4f6b-a085-1d517071516c.png)

Et les données sont également visibles dans l'application lorsque l'on souhaite créer une nouvelle zone humide: 
![capture_ecran_saisie_zones_humides](https://user-images.githubusercontent.com/103249990/185889440-c85b722d-1084-4d95-815c-59a49cd769f8.png)

Je me demande donc si ce problème ne provient pas de l'interface web de l'application. Mon domaine de connaissances étant pour le moment plutôt limité en développement web, je ne saurais comment résoudre ce problème: auriez-vous une idée d'où ce problème d'affichage pourrait provenir, et comment le résoudre ? 

Nous aurions besoin de connaitre l'origine de ce problème le plus rapidement possible, car les collègues naturalistes prendrons très prochainement en main le module Zones Humides pour saisir leur données terrain. 

En espérant avoir été assez clair, et en vous remerciant par avance;
Eric L

**Comment by JulienCorny** [comment]
Bonjour, 

Merci pour votre retour. Difficile à dire comme ça, quand avez-vous installé le module ? Il y a peut-être une inadéquation entre la bdd et la version du module. Le module ZH est encore en cours de développement, même s'il est quasiment en version finale. Nous allons sortir une release très bientôt. 

En attendant, il faut mettre à jour le module (branche dev) régulièrement et vérifier dans les commits qu'il n'y a pas de modif de bdd depuis la dernière install/maj que vous avez faite, et les executer le cas échéant. Le plus simple, si vous n'avez fait que des saisies de tests serait de réinstaller le module à chaque fois (en supprimant aussi le schema pr_zh en bdd), pour être sûr que les modif de bdd sont bien à jour. Une fois la release sortie, le processus de mise à jour sera plus simple. 

J'ai mis à jour le module (pull de la branch dev) sur 2 instances GeoNature (en 2.6.2 et 2.9.1) pour tester et je n'arrive pas à reproduire ce bug.

**Comment by camillemonchicourt** [comment]
Sans retour sur ce ticket, je le ferme.
A voir si d'autres reproduisent.

**Comment by CGuillaume** [comment]
Oui merci Camille ! Nous avons refait une installation du module clean et ça fonctionne bien. On va bientôt finaliser l'import des données.

**Comment by camillemonchicourt** [comment]
OK pour le moment n'est compatible qu'avec GeoNature 2.9 et pas encore avec les versions 2.10 et 2.11 (voir le ticket sur le sujet).
