### ISSUE TITLE
MCD v2

### ISSUE THREAD

**Issue by JulienCorny** [PnX-SI/gn_module_ZH#5]
![MCD_ZH_20220831](https://user-images.githubusercontent.com/40057801/187691416-b3f5fe36-e659-46b0-ac2b-3bf9f99e5b6f.png)

**Comment by JulienCorny** [comment]
MCD avec commentaires sur les tables et champs (avec seulement le schema pr_zh et sans fk vers d'autres schémas)

![MCD_ZH_pr_zh_with_comments_20220831](https://user-images.githubusercontent.com/40057801/187690831-abd397b9-143a-4bbf-9aec-50423be59ab0.png)

**Comment by camillemonchicourt** [comment]
OK cool, à voir si c'est le MCD définitif de la version 1.0.0, ou si il a évolué encore depuis ?

Peut-etre mettre le MCD définitif dans la doc, et fermer ce ticket ?

**Comment by JulienCorny** [comment]
oui il est bien dans la doc : 
- https://github.com/PnX-SI/gn_module_ZH/tree/main/doc
- utilisé dans https://github.com/PnX-SI/gn_module_ZH/blob/main/doc/hierarchy.md

Il restera peut être à ajouter la précision 4326 pour les geom, suite à https://github.com/PnX-SI/gn_module_ZH/pull/15/commits/7d77aa82c54703b8eac8eba41c85495b062e71e7
